version: '3'

services:
  database:
    build:
      context: _database/
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SQL_HOST=database
      - SQL_WAIT=20